### ISSUE TITLE
Prematurely Evaluating a QuerySet Inside A Custom Filter Causes A Crash For Larger Datasets

### ISSUE THREAD

**Issue by rsomani95** [MrThearMan/graphene-django-query-optimizer#101]
### I have read the docs thoroughly before making this bug report.

- [X] Yes

### I have read through other open issues, and my issue is not a duplicate.

- [X] Yes

### What version of the library you are using?

0.5.2

### Which python version are you using?

3.12

### What operating system are you on?

Mac

### Description

I have a custom `FilterSet` where I _need_ to prematurely evaluate the queryset to support some functionality. I'm not diving into specifics because it may distract from the main issue (but happy to later if it is enlightening), however I've managed to replicate this with the test models. 

```python
# Custom FilterSet

class PropertyManagerFilterSet(FilterSet):
    dummy_eval_qset_prematurely = TypedFilter(graphene.String, method="filter_dummy_eval_qset_prematurely")

    def filter_dummy_eval_qset_prematurely(
        self, qs: QuerySet[PropertyManager], name: str, value: str
    ) -> QuerySet[PropertyManager]:
        candidate_ids = list(qs.values_list("id", flat=True))
        scoped_qs = (
            PropertyManager.objects
            .filter(id__in=candidate_ids)
            .annotate(random_val=Value(0.0, models.FloatField()))
        )
        return scoped_qs
```

```graphql
{
  pagedPropertyManagers(dummyEvalQsetPrematurely: "<>") {
    edges {
      node {
        id
      }
    }
  }
}
```

This runs fine for a small dataset of 10 samples (the default).

However, when I scale this up to 2 million property managers, I run into the following error:
```python
2024-05-06T20:05:41+0000 | INFO | project.logging.resolve:40 | Traceback (most recent call last):
  File "/Users/rahulsomani/miniconda3/envs/gql/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsomani/miniconda3/envs/gql/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: too many SQL variables

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rahulsomani/git/graphene-django-query-optimizer/tests/project/logging.py", line 38, in resolve
    return next(root, info, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsomani/git/graphene-django-query-optimizer/query_optimizer/fields.py", line 289, in connection_resolver
    queryset.count()
  File "/Users/rahulsomani/miniconda3/envs/gql/lib/python3.12/site-packages/django/db/models/query.py", line 608, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsomani/miniconda3/envs/gql/lib/python3.12/site-packages/django/db/models/sql/query.py", line 568, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsomani/miniconda3/envs/gql/lib/python3.12/site-packages/django/db/models/sql/query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsomani/miniconda3/envs/gql/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/Users/rahulsomani/miniconda3/envs/gql/lib/python3.12/site-packages/graphene_django/debug/sql/tracking.py", line 153, in execute
    return self._record(self.cursor.execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsomani/miniconda3/envs/gql/lib/python3.12/site-packages/graphene_django/debug/sql/tracking.py", line 99, in _record
    return method(sql, params)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsomani/miniconda3/envs/gql/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsomani/miniconda3/envs/gql/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 160, in _record
    return method(sql, params)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsomani/miniconda3/envs/gql/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsomani/miniconda3/envs/gql/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsomani/miniconda3/envs/gql/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsomani/miniconda3/envs/gql/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/rahulsomani/miniconda3/envs/gql/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/rahulsomani/miniconda3/envs/gql/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsomani/miniconda3/envs/gql/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: too many SQL variables
```

I'm not sure if this kind of behavior is fundamentally not supported, or is there something obvious I'm missing?

FWIW, I tried running this outside the FilterSet mechanism (as a custom method that's run inside `QueryOptimizer.optimize_queryset` right after `filterset.qs` is called, but that resulted in the same behavior, which makes me think that perhaps this isn't a `django-filter` issue

**Comment by MrThearMan** [comment]
At first glance, the error indicates issues with the SQLite backend itself. Seems like the optimizer needs to add variables to the query, and this gets out of hand with large datasets. Could you provide the SQL, for example debugging with `db_query_logger` in `test/example/utils.py` to see what it's planning to execute?

**Comment by MrThearMan** [comment]
I think you might be running into [SQLITE_LIMIT_VARIABLE_NUMBER](https://www.sqlite.org/limits.html#:~:text=Maximum%20Number%20Of%20Host%20Parameters%20In%20A%20Single%20SQL%20Statement), which limits the number of variables to 32 766 in the current versions of SQLite (I suspect other databases have similar limits, since it's a means of protection). This happens due to using `.filter(id__in=candidate_ids)`, which results in the following SQL:

```sql
SELECT ... FROM "example_propertymanager" WHERE "example_propertymanager"."id" IN (%s, %s, %s, ...)
```

Where `%s` is repeated the same number of times as the `candidate_ids` list contains values, meaning it has that many variables, and thus `sqlite3.OperationalError: too many SQL variables`.

I'm classifying this a not-a-bug, and closing the issue.
