### ISSUE TITLE
Nested ManyToMany Relationships In Relay Nodes Are Broken

### ISSUE THREAD

**Issue by rsomani95** [MrThearMan/graphene-django-query-optimizer#73]
### I have read the docs thoroughly before making this bug report.

- [X] Yes

### I have read through other open issues, and my issue is not a duplicate.

- [X] Yes

### What version of the library you are using?

0.2.6

### Which python version are you using?

3.12

### What operating system are you on?

Mac

### Description

When querying a `ManyToMany` field as a nested relay node, I run into the following error:

```python
2024-03-07T04:02:05+0000 | INFO | project.logging.resolve:40 | Traceback (most recent call last):
  File "/Users/rahulsomani/git/graphene-django-query-optimizer/tests/project/logging.py", line 38, in resolve
    return next(root, info, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsomani/miniconda3/envs/gql-py11/lib/python3.11/site-packages/graphene/relay/node.py", line 106, in node_resolver
    return cls.get_node_from_global_id(info, id, only_type=only_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsomani/miniconda3/envs/gql-py11/lib/python3.11/site-packages/graphene/relay/node.py", line 131, in get_node_from_global_id
    return get_node(info, _id)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsomani/git/graphene-django-query-optimizer/query_optimizer/types.py", line 78, in get_node
    return optimize_single(queryset, info, pk=pk, max_complexity=cls._meta.max_complexity)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsomani/git/graphene-django-query-optimizer/query_optimizer/compiler.py", line 91, in optimize_single
    optimized_queryset = optimizer.optimize_queryset(queryset)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsomani/git/graphene-django-query-optimizer/query_optimizer/optimizer.py", line 72, in optimize_queryset
    results = self.compile(filter_info=filter_info)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsomani/git/graphene-django-query-optimizer/query_optimizer/optimizer.py", line 110, in compile
    self.compile_prefetch(name, optimizer, results, filter_info)
  File "/Users/rahulsomani/git/graphene-django-query-optimizer/query_optimizer/optimizer.py", line 140, in compile_prefetch
    queryset = self.paginate_prefetch_queryset(queryset, name, filter_info=filter_info)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsomani/git/graphene-django-query-optimizer/query_optimizer/optimizer.py", line 174, in paginate_prefetch_queryset
    field_name: str = field.remote_field.attname
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ManyToManyRel' object has no attribute 'attname'
```

This is the GQL setup on the Python side (slightly modified from the example):

```python
class DeveloperNode(DjangoObjectType):
    class Meta:
        model = Developer
        interfaces = (relay.Node,)


class HousingCompanyNode(IsTypeOfProxyPatch, DjangoObjectType):
    real_estates = DjangoConnectionField(RealEstateNode)

    class Meta:
        model = HousingCompanyProxy
        interfaces = (relay.Node,)
```

Breaking queries:
```graphql
# Fails
{
  pagedHousingCompanies {
    edges {
      node {
        name
        developers {
          edges {
            node {
              id
            }
          }
        }
      }
    }
  }
}

# Fails
{
  housingCompany(id:"SG91c2luZ0NvbXBhbnlOb2RlOjIw") {
    developers {
      edges {
        node {
          id
        }
      }
    }
  }
}
```

This only happens when querying `developers` as a `DjangoConnectionField`. If we set it up as a `DjangoListField`, there's no issues in the query

**Comment by MrThearMan** [comment]
Seems like I missed a case for forward many-to-many relations when determining partitioning field name for prefetch queryset windowing. Quick fix, added in [0.2.7](https://github.com/MrThearMan/graphene-django-query-optimizer/releases/tag/v0.2.7).
